server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdx?serverTimezone=UTC
    username: root
    password: x5
  security:
    user:
      name: cuiyuguang
      password: 123456